name: ExampleKMPUtilities
options:
  bundleIdPrefix: id.feinn.utilities.example
  usesTabs: false
  indentWidth: 4
  defaultConfig: Debug
targets:
  ExampleKMPUtilities:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    settings:
      MARKETING_VERSION: 1
      CURRENT_PROJECT_VERSION: 1
      GENERATE_INFOPLIST_FILE: YES
    info:
      path: Info.plist
      properties:
        CFBundleDisplayName: "Example KMP Utilities"
        UILaunchScreen:
          UIColorName: black
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        CADisableMinimumFrameDurationOnPhone: true
        LSRequiresIPhoneOS: true
        NSCameraUsageDescription: Camera permission is required to take pictures.
    preBuildScripts:
      - path: preBuild.sh
    sources:
      - path: iosApp
        buildPhase: sources
      - path: Resources
        buildPhase: resources
